[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.20"  # Choose your preferred Solidity version
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
coston2 = "${COSTON2_RPC_URL}"

[etherscan]
coston2 = { key = "${ETHERSCAN_API_KEY}", chain = 114, url = "https://coston2-explorer.flare.network/api"}